name:                vm
version:             0.1.0.0
github:              "githubuser/glados"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/glados#readme>

dependencies:
- base >= 4.7 && < 5
- HUnit
- megaparsec
- directory
- process >= 1.6.16.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

internal-libraries:
  lib:
    source-dirs: lib/
    dependencies:
    - base >= 4.7 && < 5
    - megaparsec
    - directory


executables:
  vm-exe:
    main:                Main.hs
    source-dirs:         main/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lib


tests:
  vm-test:
    main:                UnitTests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lib
