name: Release CI/CD

on:
  release:
    types:
      - "created"

env:
  # All binaries separated by ' '
  EXECUTABLES: "glados"
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-FUN-500-PAR-5-1-glados-deniz.uzuntok-husson.git"

jobs:
  release:
    name: Build & Test & Upload Artifacts

    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - name: Setup
        run: stack setup --allow-different-user
      - name: Build
        run: make
        timeout-minutes: 2
      - name: Check if all files exist
        run: |
          for file in $EXECUTABLES; do
            if test -f "$file"; then
              echo "File $file exists"
            else
              echo "File $file does not exist"
              exit 1
            fi
          done
      - name: Run tests
        run: make tests
      - name: Upload Assets
        uses: dream-encode/upload-release-asset-node16@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_owner: ${{ github.event.repository.owner.login }}
          repo_name: ${{ github.event.repository.name }}
          release_id: ${{ github.event.release.id }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./glados
          asset_name: glados
          asset_content_type: "application/octet-stream"
